CREATE SCHEMA HEALTHYPETVET;
GO

USE p6g4

CREATE TABLE HEALTHYPETVET.VETERINARIO(
		Nome VARCHAR(150) NOT NULL,
		NIF int NOT NULL UNIQUE,
		Contacto int NOT NULL,
		DataNascimento DATE NOT NULL,
		NLicencaVet int IDENTITY(1,1),
		PRIMARY KEY (NLicencaVet)
);

CREATE TABLE HEALTHYPETVET.ENFERMEIRO(
		Nome VARCHAR(150) NOT NULL,
		NIF int NOT NULL UNIQUE,
		Contacto int NOT NULL,
		DataNascimento DATE NOT NULL,
		NLicencaEnf int IDENTITY(1,1),
		PRIMARY KEY (NLicencaEnf)
);

CREATE TABLE HEALTHYPETVET.CLIENTE(
		Nome VARCHAR(150) NOT NULL,
		NIF int NOT NULL UNIQUE,
		Contacto int NOT NULL,
		DataNascimento DATE NOT NULL,
		Morada VARCHAR(200) NOT NULL,
		PRIMARY KEY (NIF)
);

CREATE TABLE HEALTHYPETVET.ANIMAL(
		Nome VARCHAR(150) NOT NULL,
		Sexo CHAR(1) NOT NULL,
		Raca VARCHAR(150) NOT NULL,
		DataNascimento DATE NOT NULL,
		NDocumento int IDENTITY(1,1),
		NIFCliente int NOT NULL,
		PRIMARY KEY (NDocumento),
		FOREIGN KEY (NIFCliente) REFERENCES HEALTHYPETVET.CLIENTE(NIF) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE HEALTHYPETVET.FATURA(
		Preco float NOT NULL,
		NIFCliente int NOT NULL,
		PRIMARY KEY (NIFCliente),
		FOREIGN KEY (NIFCliente) REFERENCES HEALTHYPETVET.CLIENTE(NIF)  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE HEALTHYPETVET.MEDICAMENTOS(
		Nome VARCHAR(150) NOT NULL,
		NRegisto int IDENTITY(1,1),
		PRIMARY KEY (NRegisto)
);
CREATE TABLE HEALTHYPETVET.EPISODIO(
		Hora time NOT NULL,
		DataEpi DATE NOT NULL,
		NDocumentoAnimal int NOT NULL,
		NLicencaVet int NOT NULL,
		NEpisodio int IDENTITY(1,1),
		PRIMARY KEY (NEpisodio),
		FOREIGN KEY (NDocumentoAnimal) REFERENCES HEALTHYPETVET.ANIMAL(NDocumento)  ON DELETE CASCADE ON UPDATE CASCADE,
		FOREIGN KEY (NLicencaVet) REFERENCES HEALTHYPETVET.VETERINARIO(NLicencaVet)  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE HEALTHYPETVET.AUXILIA_EPISODIO(
		NLicencaEnf int,
		NEpisodio int,
		PRIMARY KEY (NLicencaEnf, NEpisodio),
		FOREIGN KEY (NLicencaEnf) REFERENCES HEALTHYPETVET.ENFERMEIRO(NLicencaEnf)  ON DELETE CASCADE ON UPDATE CASCADE,
		FOREIGN KEY (NEpisodio) REFERENCES HEALTHYPETVET.EPISODIO(NEpisodio)  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE HEALTHYPETVET.EXAME_EPISODIO(
		NExame int NOT NULL,
		PRIMARY KEY (NExame),
		FOREIGN KEY (NExame) REFERENCES HEALTHYPETVET.EPISODIO(NEpisodio)  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE HEALTHYPETVET.CONSULTA_EPISODIO(
		NConsulta int NOT NULL,
		PRIMARY KEY (NConsulta),
		FOREIGN KEY (NConsulta) REFERENCES HEALTHYPETVET.EPISODIO(NEpisodio)  ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE HEALTHYPETVET.RECEITA(
		NIFCliente int NOT NULL,
		NLicencaVet int NOT NULL,
		NReceita int IDENTITY(1,1),
		NConsulta int NOT NULL,
		PRIMARY KEY (NReceita),
		FOREIGN KEY (NIFCliente) REFERENCES HEALTHYPETVET.CLIENTE(NIF)  ON DELETE CASCADE ON UPDATE CASCADE,
		FOREIGN KEY (NLicencaVet) REFERENCES HEALTHYPETVET.VETERINARIO(NLicencaVet)  ON DELETE CASCADE ON UPDATE CASCADE,
		FOREIGN KEY (NConsulta) REFERENCES HEALTHYPETVET.CONSULTA_EPISODIO(NConsulta)  ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE HEALTHYPETVET.RECEITA_ORIGINA_MEDICAMENTO(
		NRegisto int NOT NULL,
		NReceita int NOT NULL,
		PRIMARY KEY (NRegisto, NReceita),
		FOREIGN KEY (NRegisto) REFERENCES HEALTHYPETVET.MEDICAMENTOS(NRegisto)  ON DELETE CASCADE ON UPDATE CASCADE,
		FOREIGN KEY (NReceita) REFERENCES HEALTHYPETVET.RECEITA(NReceita)  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE HEALTHYPETVET.CONSULTA_ORIGINA_RECEITA(
		NReceita int NOT NULL,
		NConsulta int NOT NULL,
		PRIMARY KEY (NReceita, NConsulta),
		FOREIGN KEY (NReceita) REFERENCES HEALTHYPETVET.RECEITA(NReceita)  ON DELETE CASCADE ON UPDATE CASCADE,
		FOREIGN KEY (NConsulta) REFERENCES HEALTHYPETVET.CONSULTA_EPISODIO(NConsulta)  ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE HEALTHYPETVET.CIRURGIA_EPISODIO(
		NCirurgia int NOT NULL,
		PRIMARY KEY (NCirurgia),
		FOREIGN KEY (NCirurgia) REFERENCES HEALTHYPETVET.EPISODIO(NEpisodio)  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE HEALTHYPETVET.INTERNAMENTO_EPISODIO(
		NInternamento int NOT NULL,
		PRIMARY KEY (NInternamento),
		FOREIGN KEY (NInternamento) REFERENCES HEALTHYPETVET.EPISODIO(NEpisodio)  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE HEALTHYPETVET.INTERNAMENTO_CONTEM_MEDICAMENTOS(
		NRegisto int NOT NULL,
		NInternamento int NOT NULL,
		PRIMARY KEY (NRegisto, NInternamento),
		FOREIGN KEY (NRegisto) REFERENCES HEALTHYPETVET.MEDICAMENTOS(NRegisto)  ON DELETE CASCADE ON UPDATE CASCADE,
		FOREIGN KEY (NInternamento) REFERENCES HEALTHYPETVET.INTERNAMENTO_EPISODIO(NInternamento)  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE HEALTHYPETVET.EPISODIO_GERA_FATURA(
		NIFCliente int NOT NULL,
		NEpisodio int NOT NULL,
		PRIMARY KEY (NIFCliente, NEpisodio),
		FOREIGN KEY (NIFCliente) REFERENCES HEALTHYPETVET.CLIENTE(NIF)  ON DELETE CASCADE ON UPDATE CASCADE,
		FOREIGN KEY (NEpisodio) REFERENCES HEALTHYPETVET.EPISODIO(NEpisodio)  ON DELETE NO ACTION ON UPDATE NO ACTION
);


--DROP TABLE HEALTHYPETVET.EPISODIO_GERA_FATURA
--DROP TABLE HEALTHYPETVET.INTERNAMENTO_CONTEM_MEDICAMENTOS
--DROP TABLE HEALTHYPETVET.INTERNAMENTO_EPISODIO
--DROP TABLE HEALTHYPETVET.CIRURGIA_EPISODIO
--DROP TABLE HEALTHYPETVET.CONSULTA_ORIGINA_RECEITA
--DROP TABLE HEALTHYPETVET.RECEITA_ORIGINA_MEDICAMENTO
--DROP TABLE HEALTHYPETVET.RECEITA
--DROP TABLE HEALTHYPETVET.EXAME_EPISODIO
--DROP TABLE HEALTHYPETVET.CONSULTA_EPISODIO
--DROP TABLE HEALTHYPETVET.AUXILIA_EPISODIO
--DROP TABLE HEALTHYPETVET.EPISODIO
--DROP TABLE HEALTHYPETVET.MEDICAMENTOS
--DROP TABLE HEALTHYPETVET.FATURA
--DROP TABLE HEALTHYPETVET.ANIMAL
--DROP TABLE HEALTHYPETVET.CLIENTE
--DROP TABLE HEALTHYPETVET.ENFERMEIRO
--DROP TABLE HEALTHYPETVET.VETERINARIO